

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class TextBlock;
                ref class ComboBox;
                ref class CheckBox;
                ref class TextBox;
                ref class Slider;
            }
        }
    }
}

namespace ShadowMapping
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ErrorText;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ comboBox;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ Earth_Normal_Checkbox;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ Moon_Normal_Checkbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Distance;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ KDtree;
        private: ::Windows::UI::Xaml::Controls::Slider^ SampleCountSlider;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CurrentSampleCount;
    };
}

